"use client";
import {useCallback,useEffect,useState} from "react";import {AppShell} from "@/components/AppShell";import {Protected} from "@/components/Protected";import {Card,EmptyState,ErrorState,Pagination,PageSkeleton} from "@/components/ui";import {api,type AuditPage} from "@/lib/api";
export default function AuditLog(){const [action,setAction]=useState("");const [target,setTarget]=useState("");const [page,setPage]=useState(0);const [data,setData]=useState<AuditPage|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError("");const p=new URLSearchParams({page:String(page),size:"20"});if(action.trim())p.set("action",action.trim());if(target.trim())p.set("targetId",target.trim());try{setData(await api<AuditPage>(`/admin/audit?${p}`))}catch(e){setError(e instanceof Error?e.message:"Journal indisponible.")}finally{setLoading(false)}},[action,target,page]);useEffect(()=>{
  // The request owns the loading state for audit filters.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 return <Protected role="ADMIN"><AppShell role="ADMIN"><div className="page-stack"><header className="page-heading"><div><span className="eyebrow">Traçabilité</span><h1>Journal d’audit</h1><p>Actions administratives sensibles, en ordre antéchronologique.</p></div></header><Card className="admin-filters"><label>Action<input value={action} onChange={e=>{setAction(e.target.value);setPage(0)}} placeholder="USER_SUSPENDED"/></label><label>Cible<input inputMode="numeric" value={target} onChange={e=>{setTarget(e.target.value);setPage(0)}} placeholder="Identifiant"/></label></Card>{loading&&!data?<PageSkeleton/>:error&&!data?<ErrorState message={error} onRetry={load}/>:data&&<>{data.content.length?<div className="audit-list">{data.content.map(item=><Card key={item.id}><div className="audit-heading"><strong>{item.action}</strong><time>{new Date(item.occurredAt).toLocaleString("fr-FR")}</time></div><p>Par {item.actorName} · cible {item.targetType} {item.targetId??"—"}</p>{item.previousStatus&&<p>{item.previousStatus} → {item.newStatus}</p>}{item.reason&&<details><summary>Motif</summary><p>{item.reason}</p></details>}</Card>)}</div>:<EmptyState title="Aucun événement" description="Aucune action ne correspond aux filtres actuels."/>}<Pagination page={data.page} totalPages={data.totalPages} onPrevious={()=>setPage(v=>Math.max(0,v-1))} onNext={()=>setPage(v=>v+1)}/></>}</div></AppShell></Protected>}
