sonar.organization=hatim-koubri
sonar.projectKey=hatim-koubri_E-learning
sonar.projectName=E-learning
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,web/app,web/components,web/lib
sonar.tests=backend/src/test/java,web/tests
sonar.test.inclusions=backend/src/test/java/**/*.java,web/tests/**/*.test.ts,web/tests/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/coverage/**,**/*.d.ts,web/next.config.*,web/eslint.config.mjs
sonar.coverage.exclusions=backend/src/main/java/ma/elearning/ElearningApplication.java,backend/src/main/java/ma/elearning/config/**,backend/src/main/java/ma/elearning/api/*Dtos.java,backend/src/main/java/ma/elearning/formation/*Status.java,backend/src/main/java/ma/elearning/formation/*Type.java,backend/src/main/java/ma/elearning/learning/*Statut.java,backend/src/main/java/ma/elearning/learning/TypeAcces.java,backend/src/main/java/ma/elearning/learning/ModePaiement.java,backend/src/main/java/ma/elearning/quiz/TentativeStatut.java,web/app/**/layout.tsx

sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.java.source=21
sonar.java.libraries=backend/target/sonar-libraries/*.jar
sonar.java.test.libraries=backend/target/sonar-libraries/*.jar
sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info
