"use client";
import Link from "next/link";import {useParams} from "next/navigation";import {useCallback,useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";import {Protected} from "@/components/Protected";import {Alert,Badge,Button,Card,ErrorState,Modal,PageSkeleton} from "@/components/ui";
import {api,type AdminUserDetail,type DeletionImpact} from "@/lib/api";
type Action="suspend"|"reactivate"|"delete"|null;
export default function UserDetailPage(){const {id}=useParams<{id:string}>();const [data,setData]=useState<AdminUserDetail|null>(null);const [impact,setImpact]=useState<DeletionImpact|null>(null);const [action,setAction]=useState<Action>(null);const [reason,setReason]=useState("");const [confirmation,setConfirmation]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{setData(await api<AdminUserDetail>(`/admin/utilisateurs/${id}`));setError("")}catch(e){setError(e instanceof Error?e.message:"Utilisateur introuvable.")}finally{setLoading(false)}},[id]);useEffect(()=>{
  // The request owns the initial detail loading state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 async function openDelete(){setError("");try{setImpact(await api<DeletionImpact>(`/admin/utilisateurs/${id}/suppression-impact`));setAction("delete")}catch(e){setError(e instanceof Error?e.message:"Analyse impossible.")}}
 async function submit(){if(!data||!action)return;setBusy(true);setError("");try{if(action==="suspend")await api(`/admin/utilisateurs/${id}/suspension`,{method:"POST",body:JSON.stringify({motif:reason,expectedVersion:data.user.version})});if(action==="reactivate")await api(`/admin/utilisateurs/${id}/reactivation`,{method:"POST",body:JSON.stringify({motif:reason,expectedVersion:data.user.version})});if(action==="delete"&&impact)await api(`/admin/utilisateurs/${id}`,{method:"DELETE",body:JSON.stringify({confirmation,expectedMode:impact.mode,expectedVersion:impact.version})});setAction(null);setReason("");setConfirmation("");setNotice("Action enregistrée et données serveur rechargées.");await load()}catch(e){setError(e instanceof Error?e.message:"L’action a échoué.");await load()}finally{setBusy(false)}}
 return <Protected role="ADMIN"><AppShell role="ADMIN"><div className="page-stack"><Link href="/admin/utilisateurs">← Retour aux utilisateurs</Link>{loading&&!data?<PageSkeleton/>:error&&!data?<ErrorState message={error} onRetry={load}/>:data&&<><header className="page-heading"><div><span className="eyebrow">Compte #{data.user.id}</span><h1>{data.user.nom}</h1><p>{data.user.email}</p></div><Badge variant={data.user.statut==="ACTIF"?"success":"warning"}>{data.user.statut}</Badge></header>{notice&&<Alert variant="success">{notice}</Alert>}{error&&<Alert variant="error">{error}</Alert>}<div className="admin-detail-grid"><Card><h2>Identité</h2><dl><dt>Rôle</dt><dd>{data.user.role}</dd><dt>Téléphone</dt><dd>{data.user.telephone||"Non renseigné"}</dd><dt>Créé le</dt><dd>{new Date(data.user.createdAt).toLocaleString("fr-FR")}</dd><dt>Version</dt><dd>{data.user.version}</dd></dl></Card><Card><h2>Relations métier</h2><dl>{Object.entries(data.relations).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></Card></div><Card className="admin-actions"><h2>Actions sécurisées</h2>{data.suspendable&&<Button variant="danger" onClick={()=>setAction("suspend")}>Suspendre</Button>}{data.reactivatable&&<Button onClick={()=>setAction("reactivate")}>Réactiver</Button>}{data.deletable&&<Button variant="danger" onClick={openDelete}>Analyser la suppression</Button>}</Card></>}
 <Modal open={action==="suspend"||action==="reactivate"} title={action==="suspend"?"Suspendre le compte":"Réactiver le compte"} description="Le motif est conservé dans le journal d’audit." onClose={()=>!busy&&setAction(null)}><label>Motif<textarea autoFocus maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="modal-actions"><Button variant="secondary" onClick={()=>setAction(null)} disabled={busy}>Annuler</Button><Button loading={busy} disabled={!reason.trim()} onClick={submit}>Confirmer</Button></div></Modal>
 <Modal open={action==="delete"} title={impact?.mode==="SUPPRESSION_PHYSIQUE"?"Suppression physique":"Anonymisation définitive"} description={impact?.explanation} onClose={()=>!busy&&setAction(null)}>{impact&&<><ul>{Object.entries(impact.relations).map(([k,v])=><li key={k}>{k} : {v}</li>)}</ul><label>Recopiez l’e-mail exact<input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div className="modal-actions"><Button variant="secondary" onClick={()=>setAction(null)}>Annuler</Button><Button variant="danger" loading={busy} disabled={confirmation!==data?.user.email} onClick={submit}>Confirmer définitivement</Button></div></>}</Modal>
 </div></AppShell></Protected>}
