"use client";
import{FormEvent,useCallback,useEffect,useState}from"react";
import{api}from"@/lib/api";import{Classe,Session}from"@/lib/classes";import{FormationSummary}from"@/lib/formations";import{Protected}from"@/components/Protected";
type Eligible={id:number;nom:string;email:string};
const timezone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
const iso=(value:FormDataEntryValue|null)=>new Date(String(value)).toISOString();
export default function Page(){
 const[items,setItems]=useState<Classe[]>([]),[formations,setFormations]=useState<FormationSummary[]>([]),[eligible,setEligible]=useState<Record<number,Eligible[]>>({}),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{setItems(await api("/formateur/classes"));setFormations(await api("/formateur/formations"));setError("")}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{Promise.all([api<Classe[]>("/formateur/classes"),api<FormationSummary[]>("/formateur/formations")]).then(([c,f])=>{setItems(c);setFormations(f)}).catch(e=>setError((e as Error).message))},[]);
 async function submitClass(e:FormEvent<HTMLFormElement>,id?:number){e.preventDefault();const d=new FormData(e.currentTarget),payload={formationId:Number(d.get("formationId")),nom:d.get("nom"),description:d.get("description"),capacite:Number(d.get("capacite")),dateDebut:d.get("dateDebut"),dateFin:d.get("dateFin")};try{await api(id?`/formateur/classes/${id}`:"/formateur/classes",{method:id?"PUT":"POST",body:JSON.stringify(payload)});setNotice(id?"Classe modifiée.":"Classe créée.");await load()}catch(x){setError((x as Error).message)}}
 async function submitSession(e:FormEvent<HTMLFormElement>,classId:number,id?:number){e.preventDefault();const d=new FormData(e.currentTarget),payload={titre:d.get("titre"),dateDebut:iso(d.get("debut")),dateFin:iso(d.get("fin")),fuseauHoraire:timezone()};try{await api(id?`/formateur/seances/${id}`:`/formateur/classes/${classId}/seances`,{method:id?"PUT":"POST",body:JSON.stringify(payload)});setNotice(id?"Séance modifiée.":"Séance planifiée.");await load()}catch(x){setError((x as Error).message)}}
 async function candidates(id:number){try{const list=await api<Eligible[]>(`/formateur/classes/${id}/participants-eligibles`);setEligible(v=>({...v,[id]:list}))}catch(e){setError((e as Error).message)}}
 async function assign(classId:number,participantId:number){try{await api(`/formateur/classes/${classId}/membres`,{method:"POST",body:JSON.stringify({participantId})});setNotice("Participant affecté.");await load();await candidates(classId)}catch(e){setError((e as Error).message)}}
 async function cancel(s:Session){if(!confirm(`Annuler « ${s.titre} » ?`))return;try{await api(`/formateur/seances/${s.id}/annulation`,{method:"POST"});await load()}catch(e){setError((e as Error).message)}}
 async function join(id:number){try{const j=await api<{joinUrl:string}>(`/formateur/seances/${id}/join`);location.assign(j.joinUrl)}catch(e){setError((e as Error).message)}}
 return <Protected role="FORMATEUR"><main><h1>Classes virtuelles</h1><p>Créez les groupes, affectez les participants éligibles et planifiez les séances.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success">{notice}</p>}
 <form onSubmit={e=>submitClass(e)} className="card"><h2>Nouvelle classe</h2><ClassFields formations={formations}/><button>Créer la classe</button></form>
 {items.map(c=><section className="card" key={c.id}><h2>{c.nom}</h2><details><summary>Modifier la classe</summary><form onSubmit={e=>submitClass(e,c.id)}><ClassFields formations={formations} value={c}/><button>Enregistrer</button></form></details>
 <h3>Participants ({c.membres.length}/{c.capacite})</h3>{c.membres.length?<ul>{c.membres.map(m=><li key={m.id}>{m.nom} — {m.email}</li>)}</ul>:<p>Aucun participant affecté.</p>}<button onClick={()=>candidates(c.id)}>Afficher les participants éligibles</button>{eligible[c.id]?.map(p=><p key={p.id}>{p.nom} — {p.email} <button onClick={()=>assign(c.id,p.id)}>Affecter</button></p>)}
 <h3>Séances</h3><form onSubmit={e=>submitSession(e,c.id)}><SessionFields/><button>Planifier</button></form>{c.seances.map(s=><article key={s.id}><h4>{s.titre}</h4><p>{new Date(s.dateDebut).toLocaleString()} — {new Date(s.dateFin).toLocaleString()} ({s.statut})</p>{s.statut==="PLANIFIEE"&&<><button onClick={()=>join(s.id)}>Ouvrir Jitsi</button><button onClick={()=>cancel(s)}>Annuler</button><details><summary>Modifier</summary><form onSubmit={e=>submitSession(e,c.id,s.id)}><SessionFields value={s}/><button>Enregistrer</button></form></details></>}</article>)}</section>)}</main></Protected>
}
function ClassFields({formations,value}:{formations:FormationSummary[];value?:Classe}){return <div className="form-grid"><label>Formation<select name="formationId" required defaultValue={value?.formationId}>{formations.filter(f=>f.statut==="PUBLIEE").map(f=><option key={f.id} value={f.id}>{f.titre}</option>)}</select></label><label>Nom<input name="nom" required maxLength={180} defaultValue={value?.nom}/></label><label>Description<textarea name="description" maxLength={10000} defaultValue={value?.description}/></label><label>Capacité<input name="capacite" type="number" min="1" required defaultValue={value?.capacite??20}/></label><label>Début<input name="dateDebut" type="date" required defaultValue={value?.dateDebut}/></label><label>Fin<input name="dateFin" type="date" required defaultValue={value?.dateFin}/></label></div>}
function SessionFields({value}:{value?:Session}){const local=(v?:string)=>v?new Date(v).toISOString().slice(0,16):undefined;return <div className="form-grid"><label>Titre<input name="titre" required maxLength={180} defaultValue={value?.titre}/></label><label>Début<input name="debut" type="datetime-local" required defaultValue={local(value?.dateDebut)}/></label><label>Fin<input name="fin" type="datetime-local" required defaultValue={local(value?.dateFin)}/></label></div>}
